stages:
  prepare:
    cmd: python src/prepare.py -f data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py -i data/prepared -o data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.bias_1
    - featurize.multiplier_1
    outs:
    - data/features
  train:
    cmd: python src/train.py -i data/features -o model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.c
    - train.seed
    outs:
    - model.pkl
