stages:
  prepare:
    cmd: python src/prepare.py -f data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py -i data/prepared -o data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.bias_1
    - featurize.multiplier_1
    outs:
    - data/features
  train:
    cmd: python src/train.py -i data/features -o model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py -mfp model.pkl -ffp data/features -sfp scores.json
      -pfp prc.json
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
